### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by DeCalvin2006** [iotang/cxk-ball#1]
**这个功能是否与你所遇到的问题有关？**

是的.

**描述你想要的功能或建议**

Firefox 75.0

在较高球速(~~大概在0以上~~在5时最明显)时,__如果使用Q技能让球横向飞向砖块(需另一边清空)__,球会加速&出现穿透砖块的Bug.建议修复.~~虽然这样可以快速通关~~

**你是否有可用的备选方案？**

没有.

**附加内容**

_~~不需要的东西都划掉了~~_

我不想听到诸如 "__此游戏只能在Chrome浏览器上完美运行__"之类的回复.

__~~Because IE is Still there in your Computer Room.~~__

**Comment by iotang** [comment]
这就是主 Q 流的操作，恭喜你已经掌握了主 Q 流的流派。
